// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_increase_passwordlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_increase_passwordlength));
        
        string IMigrationMetadata.Id
        {
            get { return "202512110023255_mig_increase_passwordlength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
